spring:
  application:
    name: news
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
#  security:
#    user:
#      name: test
#     password: test1
#      roles: test
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] ${HOSTNAME}"
  file:
    name: ${news.log.dir:target}/news.log
  level:
    sql: debug
    web: debug
    '[io.github.merite.training]': debug
